services:
  painting-layout-dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  painting-layout-prod:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    profiles:
      - prod
    environment:
      - NODE_ENV=production

volumes:
  node_modules:
